fission-codes/fission

app/Main.hs
ipfs-api.cabal
package.yaml
stack.yaml

Setup EKG Monitoring

---

ipfs-api.cabal
package.yaml
src/Fission/File.hs
src/Fission/IPFS/Types.hs
src/Fission/Internal/Orphanage.hs
src/Fission/Plan.hs
src/Fission/Platform/Heroku/Provision.hs
src/Fission/Platform/Heroku/Types.hs
src/Fission/Platform/Heroku/UserConfig.hs
src/Fission/Security.hs
src/Fission/Storage/IPFS.hs
src/Fission/Storage/Types.hs
src/Fission/User.hs
src/Fission/Web.hs
src/Fission/Web/Heroku.hs
src/Fission/Web/IPFS.hs
src/Fission/Web/IPFS/Upload.hs
src/Fission/Web/IPFS/Upload/Multipart.hs
src/Fission/Web/Ping.hs
src/Fission/Web/Routes.hs
src/Fission/Web/Swagger.hs
src/Fission/Web/Types.hs

Set up Swagger

---

app/Main.hs
fission-web-api.cabal
src/Fission/Config/Types.hs
src/Fission/File/Types.hs
src/Fission/IPFS/Error.hs
src/Fission/IPFS/Peer.hs
src/Fission/IPFS/Peer/Error.hs
src/Fission/IPFS/Process.hs
src/Fission/IPFS/Types.hs
src/Fission/Internal/Orphanage.hs
src/Fission/Storage/IPFS.hs
src/Fission/Web.hs
src/Fission/Web/Error.hs
src/Fission/Web/IPFS.hs
src/Fission/Web/IPFS/Download.hs
src/Fission/Web/IPFS/Pin.hs
src/Fission/Web/IPFS/Upload.hs
src/Fission/Web/IPFS/Upload/Multipart.hs
src/Fission/Web/IPFS/Upload/Simple.hs
src/Fission/Web/Log.hs

```bash
curl \
-s \
-H "Accept: application/octet-stream" \
-H "Authorization: Basic abcdef" \
http://localhost:1337/ipfs/QmePw8gVcBMb8x6kAep6aMBAX23hCSk6iZW3i9VKkiFhu1
```
```bash
curl \
-s \
-H "Accept: application/octet-stream" \
-H "Authorization: Basic abcdef" \
"http://localhost:1337/ipfs?cid=QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ/cat.jpg" \
> ~/Desktop/foo.jpg
```

Download files

---

.gitignore
README.md
app/Main.hs
fission-web-api.cabal
package.yaml

TLS Support

---

app/Main.hs
fission-web-api.cabal
package.yaml

Set up CORS

---

app/Main.hs
fission-web-api.cabal
src/Fission/Web/CORS.hs

CORS was set to only work for `GET`, `HEAD` and `POST`
Add `PUT` and `DELETE`

Add PUT & DLEETE as allowed CORS method

---

fission-web-api.cabal
package.yaml

Update maintainers in package.yaml

---

fission-cli/Main.hs
library/Fission/CLI.hs
library/Fission/CLI/Command/Down.hs
library/Fission/CLI/Command/Login.hs
library/Fission/IPFS/Process.hs
library/Fission/Storage/IPFS.hs
library/Fission/Web/IPFS/Download.hs
package.yaml

Making a few changes to #148 after the changes in #149

Fission Down ⬇️

---

library/Fission/Internal/Exception.hs
package.yaml

Helpers to use `Control.Monad.Exception` in our CLI stack

Exception helpers

---

library/Fission/CLI.hs
library/Fission/CLI/Command/Watch.hs
package.yaml

**Summary**
Ensures we output DNS info on `watch` being first run
**Closing issues**
Closes #158

Ensure DNS info is displayed on watch

---

library/Fission/CLI/Auth.hs
library/Fission/CLI/Command/Login.hs
library/Fission/CLI/Command/Register.hs
library/Fission/CLI/Command/Up.hs
library/Fission/CLI/Command/Watch.hs
library/Fission/CLI/Config/Types.hs
library/Fission/CLI/Display/Error.hs
library/Fission/CLI/Pin.hs

Pairing on 116

---

README.md
library/Fission/Internal/Development.hs

**Summary**
The database instructions didn't work anymore, this PR fixes that.
**Test plan (required)**
Ran through the listed steps in `stack repl`.

Update database setup instructions n README

---

README.md

No link to cli repo
Added note about breaking the cli out into it's own repo w/ link

Add link to cli repo

---

library/Fission/User/Mutate.hs
library/Fission/User/Password.hs
library/Fission/User/Password/Types.hs
library/Fission/Web/User/Password/Reset.hs
library/Fission/Web/User/Password/Reset/Types.hs

I need to run to a meeting like... now!
But @dholms this is a slightly more idiomatic version. It's more code, but also a cleaner, more reusable, &c. I can walk you through it later in our one-on-one 👍
---
> ...Later...
Welp, I merged the last PR, and then realized that the `Maybe` was at the wrong layer 😅

More idiomatic password reset without Maybe

---

library/Fission/Web/User.hs

PUT `/user/reset_password` route got deleted during rebase
re-add route

Fix user routes from rebase

---

library/Fission/File/Types.hs
library/Fission/IPFS/CID/Types.hs
library/Fission/IPFS/Peer/Types.hs
library/Fission/IPFS/SparseTree/Types.hs
library/Fission/Internal/Orphanage/MultipartForm.hs
library/Fission/Internal/UTF8.hs
library/Fission/Platform/Heroku/Provision.hs
library/Fission/Web/Swagger.hs
library/Fission/Web/Types.hs
library/Fission/Web/User/Password/Reset/Types.hs

Fixing these makes our openapi spec valid again
closes #207

Fix Swagger Docs to allow for codegeneration

---

README.md
app/Fission/Internal/Development.hs
app/Fission/Storage/PostgreSQL.hs
app/Main.hs
library/Fission/App.hs
library/Fission/Environment.hs
test/coverage-code/Main.hs
test/coverage-docs/Main.hs

Changes the `RIO_VERBOSE` env var to `DEBUG`
closes #198

Change RIO_VERBOSE -> DEBUG

---

library/Fission/Web/Error.hs

A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
For more information, see the `CONTRIBUTING` guide.
Updates the status codes to better represent what when wrong
I'd ideally like to catch IPFS errors deeper in our stack. Like when go-ipfs gets an invalid cid. It will throw a `500` causing us to throw an `UnknownAddError`.
Ideally I'd love to have access to the internal message from ipfs-go describing why it failed so ive been tinkering with `ipfs-haskell` to see if thats possible.
Fixes #

Update IPFS status codes

---

library/Fission/Models.hs

Whoopsie 😅 
We had decided to go with the Persistent conventions. Here's that change.

Plural tables -> singular

---

library/Fission/Models.hs
library/Fission/User/CID/Mutation.hs
library/Fission/Web/Heroku/Deprovision.hs
library/Fission/Web/IPFS/CID.hs
library/Fission/Web/IPFS/Pin.hs
sql/1576714308_selda_to_persistent.sql
sql/README.md

A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
For more information, see the `CONTRIBUTING` guide.
Adds a file used for updating our databases to the new persistent convention. Also sets up the convention for how we handle and store these types of files in the future.
1. Create a clone of your existing database
```sql
CREATE DATABASE web_api_test TEMPLATE web_api;
```
2. Open your new database
```bash
pgcli -d web_api_test
```
3. Run the sql file
```bash
\i 1576714308_selda_to_persistent.sql
```
4. Run the web-api
```bash
stack run web-api
```

Add destructive sql files

---

app/Fission/Internal/Orphanage/RIO.hs
library/Fission/AWS/Subdomain/Types.hs
library/Fission/AWS/Types.hs
library/Fission/Platform/Heroku/AddOn.hs
library/Fission/Platform/Heroku/AddOn/Class.hs
library/Fission/Web.hs
library/Fission/Web/Auth.hs
package.yaml

MonadHerokuAddOn

---

app/Fission/Internal/Orphanage/RIO.hs
library/Fission/Environment.hs
library/Fission/IPFS/Linked.hs
library/Fission/IPFS/Linked/Class.hs
library/Fission/Internal/Orphanage/OctetStream.hs
library/Fission/Internal/Orphanage/PlainText.hs
library/Fission/Prelude.hs
library/Fission/Web.hs
library/Fission/Web/IPFS.hs
library/Fission/Web/IPFS/DAG.hs
library/Fission/Web/IPFS/Peer.hs
package.yaml

MonadLinkedIPFS

---

app/Fission/Internal/Orphanage/RIO.hs
library/Fission/Web.hs
library/Fission/Web/Heroku.hs
library/Fission/Web/Heroku/Provision.hs
library/Fission/Web/Server/Reflective.hs
library/Fission/Web/Server/Reflective/Class.hs
package.yaml

Continuing the pattern from #241

MonadReflectiveServer

---

package.yaml

Add Steven to the maintainers list

---

library/Fission/Web/App/Create.hs
library/Fission/Web/App/Destroy.hs
library/Fission/Web/App/Index.hs
library/Fission/Web/App/Update.hs
library/Fission/Web/DNS.hs
library/Fission/Web/Heroku/Deprovision.hs
library/Fission/Web/Heroku/Provision.hs
library/Fission/Web/IPFS/CID.hs
library/Fission/Web/IPFS/DAG.hs
library/Fission/Web/IPFS/Download.hs
library/Fission/Web/IPFS/Peer.hs
library/Fission/Web/IPFS/Pin.hs
library/Fission/Web/IPFS/Upload.hs
library/Fission/Web/Ping.hs
library/Fission/Web/Routes.hs
library/Fission/Web/Swagger.hs
library/Fission/Web/User/Create.hs
library/Fission/Web/User/Password/Reset.hs
library/Fission/Web/User/UpdateDID.hs
library/Fission/Web/User/UpdateData.hs
library/Fission/Web/User/Verify.hs
package.yaml

Retheme Swagger UI (ReDoc)

---

library/Fission/Internal/Mock/Types.hs
library/Fission/User/Creator/Class.hs
library/Fission/User/Modifier/Class.hs
library/Fission/User/Password.hs
library/Fission/User/Registration/Types.hs
library/Fission/Web/Heroku/Provision.hs
library/Fission/Web/User.hs
library/Fission/Web/User/Create.hs
library/Fission/Web/User/Password/Reset.hs
package.yaml

HOTFIX: backwards compatability with current CLI

---

README.md

Just some simple edits, getting things up and running on the ol iMac :)

Added Setup section, fixed spelling, fixed naming of live

---

README.md
library/Fission/CLI/Display/Error.hs
library/Fission/CLI/Environment.hs
library/Fission/Web/IPFS/DAG.hs

Some simple quick fixes. 293 may be deprecated now or soon anyway since I think we do setup now.
Feel free to edit DAG docs directly.

Docs and Error Messages

---

README.md

A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
For more information, see the `CONTRIBUTING` guide.
Explain the **motivation** for making this change. What existing problem does the pull request solve?
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Fixes #

Update links for install & getting started

---

cli/Main.hs
package.yaml

Use system IPFS

---

package.yaml
stack.yaml

Bump to get this change: https://github.com/fission-suite/ipfs-haskell/pull/17

Bump `ipfs-haskell` to v1.1.2

---

fission-core/library/Fission/Error/NotFound/Types.hs
fission-core/library/Fission/Web/Auth.hs
fission-core/package.yaml

May help to clarify problem space of #398

Report more context on 404s

---

fission-cli/library/Fission/CLI/Connected.hs

verififcation --> verification

Spelling correction

---

default.nix
nix/pkgs.nix
release.nix
result

Set up for cross-compile. Currently compiles down to NixOS, but this is a precursor to a fully static MUSL build.

default.nix & release.nix

---

fission-cli/library/Fission/CLI.hs
fission-cli/library/Fission/CLI/App.hs
fission-cli/library/Fission/CLI/Handler/App/Init.hs
fission-cli/library/Fission/CLI/Handler/App/Publish.hs
fission-cli/library/Fission/CLI/Handler/Setup.hs

Error code on exit fix 2

---

fission-cli/library/Fission/CLI.hs
fission-cli/library/Fission/CLI/App.hs
fission-cli/library/Fission/CLI/Handler/App/Init.hs
fission-cli/library/Fission/CLI/Handler/App/Publish.hs
fission-cli/library/Fission/CLI/Handler/Setup.hs
fission-cli/library/Fission/CLI/Handler/User/Register.hs

Direct fix

---

.github/workflows/ci.yaml
fission-web-server/library/Fission/Web/Server/Internal/Production.hs
fission-web-server/library/Fission/Web/Server/Internal/Tasks.hs
fission-web-server/server/Main.hs
nix/commands.nix
shell.nix
stack.yaml
stack.yaml.lock

Creates a delete user function (helper for support requests) to clear out a user's data.

Delete user task 

---

fission-cli/library/Fission/CLI/Display/Wait.hs
fission-cli/library/Fission/CLI/Handler/App/Init.hs
fission-cli/library/Fission/CLI/IPFS/Connect.hs
fission-cli/library/Fission/CLI/Release.hs

Better CLI contrasts

---

nix/commands.nix

Improve command syntax, add help index

---

.github/workflows/ci.yaml
fission-core/library/Fission/Error/GenericError/Types.hs
fission-core/library/Fission/Web/Async.hs
fission-web-server/library/Fission/Web/Server/IPFS/Cluster/Class.hs
fission-web-server/library/Fission/Web/Server/Types.hs
fission-web-server/package.yaml
nix/commands.nix

Well, this is what I get for having written most of the original code at like 2am 🤷‍♀️ 
Will test on staging before merging 🧪 
Big thanks to Boris for reporting, and I swear this wasn't an all evening thing. Both what the problem likely was and the solution literally came to me while I was brushing my teeth 🦷🧹

Meaningful IPFS cluster timeout ⏱

---

.github/workflows/artifacts-nix.yaml
.github/workflows/ci-nix.yaml
fission-cli/library/Fission/CLI/Environment.hs
fission-cli/library/Fission/CLI/Environment/OS/Types.hs
fission-cli/library/Fission/CLI/Handler/App/Publish.hs
fission-cli/library/Fission/CLI/Handler/Setup.hs
fission-cli/library/Fission/CLI/Handler/User/Login.hs
fission-cli/library/Fission/CLI/IPFS/Daemon.hs
fission-cli/library/Fission/CLI/IPFS/Executable.hs
fission-cli/library/Fission/CLI/Prompt.hs
fission-cli/library/Fission/CLI/Types.hs
fission-cli/package.yaml

Closes #478 
~~* [ ] Starting IPFS server for the first time~~ Not required, no longer start the daemon in setup

Implement CLI linking UI feedback

---

.github/workflows/artifacts-nix.yaml
.github/workflows/ci-nix.yaml
nix/sources.json

Works on my machine:tm:
Now to see if it will build on CI

Bump Niv dependencies

---

fission-web-server/library/Fission/Web/Server/Types.hs
fission-web-server/package.yaml
nix/fission-web-server.nix

Don't create an app if the domain name to associate with is already taken

---

fission-cli/library/Fission/CLI/App.hs
fission-cli/library/Fission/CLI/Environment.hs
fission-cli/library/Fission/CLI/Environment/Types.hs
fission-cli/library/Fission/CLI/IPFS/Ignore.hs
fission-cli/library/Fission/CLI/Parser/Config/IPFS.hs
fission-cli/package.yaml

1. Typo in the `FromJSON` field name 😅 
2. Include the app-specific ignore in that one important scenario

🐛 Fix ipfsignore

---

fission-web-server/library/Fission/Web/Server/Email/Error.hs

Let user know when their email is invalid

---

fission-cli/library/Fission/CLI/App.hs
fission-cli/library/Fission/CLI/Connected.hs
fission-cli/library/Fission/CLI/Handler/App/Init.hs
fission-cli/library/Fission/CLI/Handler/App/Publish.hs
fission-cli/library/Fission/CLI/Parser/Command/App/Up.hs
fission-cli/library/Fission/CLI/Parser/Command/App/Up/Types.hs
fission-cli/library/Fission/CLI/Parser/Open/Types.hs
fission-cli/library/Fission/CLI/Remote.hs
fission-cli/package.yaml

Add --open flag to CLI app publishing

---

fission-core/library/Fission/App/Types.hs
fission-web-api/library/Fission/Web/API/App/Index/Types.hs
fission-web-server/library/Fission/Web/Server/Handler/App/Index.hs

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
closes #385

Expose app creation/update on API

---

.github/workflows/artifacts-native.yaml
.github/workflows/artifacts-nix.yaml
.github/workflows/ci-nix.yaml
fission-core/library/Fission/User/DID/Oldstyle/Types.hs
fission-core/package.yaml
fission-core/test/Fission/Test/User/DID.hs
fission-web-server/library/Fission/Web/Server/Types.hs
fission-web-server/package.yaml
stack.yaml
stack.yaml.lock

Still need to write a couple tests to make sure that the format is _actually_ what we expect, but in theory this is done

Use oldstyle server DID when setting DNS _did

---

fission-cli/README.md

The install and getting started links needed to be updated.

Update readme with correct fission guide links

---

fission-web-server/package.yaml

I accidentally bumped the wrong version in #529 . I should've incremented the minor version. PRing this to fix this!

Correct version change

---

fission-web-api/library/Fission/Web/API/App/Index/Payload/Types.hs
fission-web-server/package.yaml

This is on me for not catching it in code review originally

Fix Swagger required fields for App Index payload
