fission-codes/fission

Dockerfile
**Summary**
`Dockerfile` contained a vestigial `.cabal` file from the scaffolding. Have since switched to Stack. This was causing issues for containers that didn't have the cache yet.
**Fixes**
**Notes**
A big thank you to @hharnisc for the report!
=> Remove vestigial cabal file copy from Docker

.gitignore, Dockerfile, ipfs-api.cabal, package.yaml
* Track `ipfs-api.cabal` again (for simplicity with Docker)
* Downgrade the tested version to `8.6.3`, again because Docker is behind
* Started building totally custom container, but have bigger fish to fry 🎣
=> Track cabal file for Docker

.travis.yml, src/Fission/Platform/Heroku/Types.hs
Very minor: remove double quotes from string, since Swagger doesn't seem to want them by default (artifact of relying on `ToJSON`)
=> Strip quotes from ToSchema Region

fission-web-api.cabal, package.yaml, src/Fission/IPFS/CID/Types.hs, src/Fission/Internal/Orphanage.hs, src/Fission/Internal/UTF8.hs, src/Fission/User/CID/Query.hs, src/Fission/User/CID/Types.hs, src/Fission/Web.hs, src/Fission/Web/IPFS.hs, src/Fission/Web/IPFS/CID.hs
1. Users should be able to see how many files they're storing
2. Many applications will use this as a "dumb" repo and just ask for everything
Add an `INDEX /ipfs/cids` endpoint, scoped to the requesting user
=> Get all CIDs for user (`INDEX /ipfs/cids`)

fission-web-api.cabal, package.yaml, src/Fission/Web/IPFS.hs, src/Fission/Web/Routes.hs
restricting fetches seems a bridge too far. Totally possible to restrict to authed users with temporary tokens and whatnot, but it would be good to be compatible with gateway APIs &c
Make the `GET /ipfs/*` endpoint not require auth
=> Public `GET /ipfs`

fission-web-api.cabal, package.yaml, src/Fission/IPFS/CID/Types.hs
In some cases, the double-quote is not present on some CIDs (during cleanup). The usual method of just removing the first and last character then lops off critical characters from the hash.
Root cause unclear 🤷‍♀️
Detect superflous double-quote, and remove.
=> Normalized `stripN`

fission-web-api.cabal, package.yaml, src/Fission/IPFS/SparseTree.hs, src/Fission/Storage/IPFS.hs
1. [X] #81 `DELETE` does not remove CID
2. [X] Inconsistent double quotes around CID shown to user
* An extra layer of double quotes were present in the output from IPFS's `stdout`
* e.g. Via log: `["\"QmQWoEjbKZhj1qpPSKUv7LRepRWTvZfvCoKBJFU9CQGrWa\""]`
* End user sees `"QmQWoEjbKZhj1qpPSKUv7LRepRWTvZfvCoKBJFU9CQGrWa"`
* This was also putting extra double quotes _in the DB_
* When we looked up the CID, we would request it as a regular string
* No matches, because the DB is full of CIDs wrapped in an extra layer of quotes
The above double-quote issue was noticed earlier in development, and assumed to be a JSON encoding issue, and handled in the `ToJSON` typeclass instance.
1 & 2. Strip the extra quotes when reading from IPFS's `stdout`
=> Fix double quotes in DB issue

README.md, src/Fission/Platform/Heroku/Provision.hs, src/Fission/Web/Heroku.hs
Heroku provision includes the `/ipfs` path. This makes it difficult to access other parts of the API.
No longer append `/ipfs` in provision
=> Remove `/ipfs` from provision host

src/Fission/Random.hs
Dollar signs cause issues when setting passwords as env variables.
Remove dollar signs in random password generation
=> Remove dollar signs from generated passwords

README.md
Quick start instructions don't work on linux because `liblzma-dev` must be installed separately
Add a note in Readme QuickStart instructions to `sudo apt install liblzma-dev` on linux
=> add note about needing to install liblzma

fission-web-api.cabal, package.yaml
* Tried LLVM backend, decided against
* Was a bit of a pain to set up
* No discernible improvement
* [This GHC GitLab Issue](https://gitlab.haskell.org/ghc/ghc/wikis/improved-llvm-backend#llvm-has-no-backwards-compatibility-guarantees) says mean things about it
* Turned on some Clang optimizations
* `h2load` tests typically seeing around a 12% improvement
* 12% is my minimum optimization threshold, so 👍
Closes #101
=> Turn on Clang backend optimzations

library/Fission/Web/IPFS/CID.hs
/ipfs/cids route returns a plaintext string. Which forces the frontend to parse it into an array of CIDs
default /ipfs/cids to return JSON, in this case an array of strings (CIDs)
=> default ipfs/cids to return JSON instead of PlainText

library/Fission/CLI/Display/Error.hs, library/Fission/CLI/Display/Success.hs
No new line after error + success messages. Terminal gets messy and hard to read
Added `\n` to error and success messages
=> add new line after error + success msgs

library/Fission/CLI/Display/Cursor.hs, library/Fission/CLI/Display/Loader.hs, library/Fission/CLI/Display/Wait.hs, library/Fission/CLI/Pin.hs, library/Fission/Web/Auth/Types.hs, package.yaml
This came up in #139. There's a LOT of `liftIO` happening in there, and it gave a confusing error about `MonadReader cfg IO`. This will squash that and tighten up the code in a few places 😃
=> Generalize several functions to MonadIO and MonadUnliftIO

example-config/env.yaml.example, fission-web/Main.hs, library/Fission/AWS/Environment/Types.hs, library/Fission/Storage/Environment/Types.hs
**Summary**
Our server was failing to start as the `env.yaml` file had a convention of camelCase when the `AWS.Enivornment.Types` were incorrectly wanting snake_case.
This was compounded by the fact that:
1. We were only matching on Right
2. The error given by Left was very undescriptive
3. Relying on Haskell guessing the type of the yaml decode made repl debugging a little harder
Note that I have changed the config values for aws on the server temporarily to be snake_case to allow for a proper review.
Once this is merged we will need to change those values back to camelCase.
=> Adjust AWS json to camelCase

library/Fission/CLI/Command/Up.hs, library/Fission/CLI/Command/Watch.hs, package.yaml
You need to `cd` into a directory that you want to sync with `up` or `watch`
Pass an optional argument to the CLI to specify a file path. May be a directory or a single file, absolute or relative
Closes https://github.com/fission-suite/web-api/issues/138
=> Add optional path argument to Up and Watch

library/Fission/AWS/Route53.hs
DNS records stick around too long so users can't see updates to their app
Decrease TTL of records from 300s to 10s
=> decrease ttl to 10 s

library/Fission/Web/User.hs, library/Fission/Web/User/Create.hs, package.yaml
Initial DNS propagation takes awhile, subsequent updates are much faster.
Set dns to point to a fission splash screen on user register. Then initial `up` will be much faster
=> Set dns to point to splash on user register

library/Fission/CLI.hs, library/Fission/CLI/Auth.hs, library/Fission/CLI/Command/Whoami.hs
Users have to check `~/.fission.yaml` to determine who they're currently logged in as
Add `whoami` command that prints user's username
Closes https://github.com/fission-suite/web-api/issues/161
=> add whoami cli command

library/Fission/CLI/Command/Down.hs, library/Fission/CLI/Command/Up.hs, library/Fission/CLI/Command/Up/Types.hs, library/Fission/CLI/Command/Watch.hs, library/Fission/CLI/Command/Watch/Types.hs, library/Fission/CLI/Command/Whoami.hs, library/Fission/CLI/Display/Success.hs, package.yaml
**Summary**
This PR fixes/implements the following **features**
_Motivation:_
I want to use the Fission CLI to keep track of my music on my local machine, without uploading all the music to the Fission "gateway". Otherwise the gateway would need to download too much data.
_Usecase:_
1. Go to music directory
2. `fission watch`
3. Add `_dnslink.fission.domain` as a source on [Diffuse](https://diffuse.sh/)
4. 🎵
**Test plan (required)**
Tested by pointing the CLI at local server, and seeing if any non-dns requests came through.
=> Add --dns-only flag

library/Fission/CLI.hs, library/Fission/CLI/Auth.hs, library/Fission/CLI/Command/Logout.hs, library/Fission/CLI/Display/Error.hs
**Summary**
Adds a `logout` command to the CLI that removes the `.fission.yaml` file
=> Fission CLI logout

Makefile, README.md
Simple change suggested by @expede 
Rename the following make commands
- `watch` -> `dev`
- `dev` -> `build`
=> Rename watch to dev, dev to build

library/Fission/Web/Error.hs, library/Fission/Web/Heroku.hs, library/Fission/Web/Log.hs, library/Fission/Web/Server.hs
Tracking issue: #140 
The Heroku add-on API has been recording 406 ("Not Acceptable") errors on de-provisioning requests. It looks like the 406 is actually on their end. We're missing two details from their docs (see next section).
Return a `Content-Type: application/vnd.heroku-addons+json; version=3`
Return a 410 on subsequent requests after 24 hours... or something? I dunno it's not totally clear. Using a 410 as failure when a record isn't found appears to be an acceptable response 🤷‍♀️ We _could_ update the add-on to track if it has been used in the past, and disambiguate between the 410 and 404, but that seems like more work than it's worth to make an external API happy.
=> Fix #140: Heroku Deprovision 406

README.md
README still references `liblzma-dev` (sqlite) instead of `libpq-dev` (postgres)
Change `liblzma` to `libpq`
=> Change liblzma to libpq

app/Main.hs, library/Fission/Web/Log.hs
Increase timeout for both clients and requesting from IPFS node to 30 minutes.
We were experiencing issues where large pins were timing out, and propagating through to the CLI.
This is already running on prod as a quick fix. Merging to master now for consistency.
=> Longer HTTP Timeout

library/Fission/Web/Swagger.hs
Missing swagger documentation on dns route. It just says `default`
Add high-level swagger documentation to route
=> DNS Swagger Docs

library/Fission/Internal/UTF8.hs, library/Fission/Prelude.hs
When reviewing a CLI PR, I realized that it may be helpful to have a printing function with automatic newlines. The base `Prelude` has `putStrLn`, which `RIO` eschews for some reason. In any case, here's some helpful functions by default to make it easier to default to printing each statement on a new line.
=> Basic text functions in `Fission.Prelude`

library/Fission/Web/IPFS/Peer.hs
GET /ipfs/peer only returns web-api node address
When a user pins something, the s3 node has to through discover the user's node through the web-api node. Sometime's this takes longer than it should. We can skip that connectivity period by returning the s3 node address as well
##Solution
return s3 node address & web-api node address on GET /ipfs/peer
Closes https://github.com/fission-suite/web-api/issues/205
=> Return s3 node on /ipfs/peers

library/Fission/Prelude.hs
`Fission.Prelude` exports `getCurrentTime` from `Data.Time` instead of `RIO.Time`. This causes some monads to not line up properly
Switch out `Data.Time` for `RIO.Time` in `Fission.Prelude`
=> Switch out Data.Time for RIO.Time in Fission.Prelude

app/Fission/Environment/IPFS/Types.hs, app/Fission/Internal/Development.hs, app/Main.hs, example-config/env.yaml.example, library/Fission/AWS.hs, library/Fission/AWS/Route53.hs, library/Fission/Config/Types.hs, library/Fission/IPFS/Gateway/Types.hs, library/Fission/IPFS/Types.hs, library/Fission/Web.hs, library/Fission/Web/DNS.hs, library/Fission/Web/User.hs, library/Fission/Web/User/Create.hs
- gateway not in env
- `domain_name` starts with a `.`
- create env variable
- add `.` to `domain_name` in code instead of env file
- refactor `registerDomain` function to eliminate WET code
A bit of clarification on variables: 
1) `ipfs.gateway` is our ipfs gateway (ie `ipfs.runfission.com`). This gets set as the cname value for any domain a user registers
2) `aws.domain_name` is the base domain name that we use for user's domain names (ie `fission.name`)
The issue (https://github.com/fission-suite/web-api/issues/162) was initially misframed because we were using `demo.runfission.com` as our `aws.domain_name` so both domains could be derived from the same base (`runfission.com`), meaning we didn't need two separate variables.
Closes https://github.com/fission-suite/web-api/issues/162
=> Gateway env

library/Fission/AWS/DomainName/Types.hs, library/Fission/Web.hs, library/Fission/Web/Swagger.hs, package.yaml
This PR introduces a handful of Swagger doc changes.
* Focus on production version
* Remove HTTP from scheme drop-down
* No longer append the port (assume 443)
* Generate valid `curl` commands
* Fix hostname (had extra quotes around it before)
* Fix docs on domain names
* Add example to domain
=> Fix Swagger docs cURL generator & domain example

package.yaml
Removes an unused dependency (at least Im pretty sure it is cc: @expede). This actually fixes an issue in building for windows. 
https://github.com/fission-suite/cli/pull/48
=> Remove streamly as it's unused

app/Fission/Environment/IPFS/Types.hs, app/Fission/Internal/Development.hs, app/Main.hs, example-config/env.yaml.example, library/Fission/Config/Types.hs, library/Fission/IPFS/Peer.hs, library/Fission/Platform/Heroku/Provision.hs, library/Fission/Web.hs, library/Fission/Web/IPFS.hs, library/Fission/Web/IPFS/Peer.hs
Moves our s3 remote peer address to our config file
closes #146
=> Move default fission peer to env var

library/Fission/App.hs
I forgot to export a key function I had wanted to use in cli to set `RIO_VERBOSE` to true
=> Export set RIO verbose

stack.yaml, stack.yaml.lock
Currently the swagger docs are broken. This is fixed by updating to the latest ipfs-haskell
=> Fix swagger docs (Update to latest ipfs-haskell)

app/Fission/Environment/AWS/Types.hs, app/Fission/Internal/Development.hs, app/Main.hs, example-config/env.yaml.example, library/Fission/AWS/Route53.hs, library/Fission/AWS/Types.hs, library/Fission/Config/Types.hs, library/Fission/Web.hs, library/Fission/Web/DNS.hs, library/Fission/Web/User.hs, library/Fission/Web/User/Create.hs
Renames `awsMock` to `route53Mock` and addresses some missed comments from @dholms in this PR: https://github.com/fission-suite/web-api/pull/225
=> Rename awsMock to route53Mock

library/Fission/Web/Error.hs, library/Fission/Web/Heroku/Deprovision.hs, library/Fission/Web/IPFS.hs, library/Fission/Web/IPFS/DAG.hs, library/Fission/Web/IPFS/Pin.hs, library/Fission/Web/IPFS/Upload.hs, library/Fission/Web/IPFS/Upload/Multipart.hs, library/Fission/Web/IPFS/Upload/Simple.hs, stack.yaml, stack.yaml.lock
In cases where we have a user readable error message from IPFS we should return it to the user so that they can debug appropriately.
_Mostly this was a fun exercise learning more Haskell_
related: https://github.com/fission-suite/ipfs-haskell/pull/9
=> Improve IPFS Error message for our API consumers

library/Fission/User/Mutation.hs, library/Fission/User/Mutation/Error.hs, library/Fission/Web/User/Create.hs
Currently we throw a 500 if a users attempts to sign up with the same email / username. 
This is incorrect and we should throw a 409.
=> Update Register to throw a 409 on unique conflict

library/Fission/User/Registration/Types.hs, library/Fission/Web/User/Create.hs
Ensure email is required only for users who sign up via the register api. Heroku still does not require an email
=> Make email required for register

package.yaml, stack.yaml, stack.yaml.lock
Switch to using the Hackage version of `ipfs-haskell`, and bump to the most recent version
=> Bump ipfs-haskell to 1.0.1

library/Fission/User/Mutation.hs
Update the Heroku Provision endpoint to throw a 409 AlreadyExists when a unique constraint error is thrown.
=> Update Heroku provision to throw 409 on unique conflict

library/Fission/Models.hs, library/Fission/Types.hs, library/Fission/Web/User/Create.hs, package.yaml
Post mortem:
* Upgrade script was restarting the wrong port [FIXED IN SCRIPT]
* DB was enforcing unique emails [WAITING ON DOMAINS TO DE-DUP USERS]
* Route53 API is now pickier about double quotes (maybe a newer API when we upgraded libs?). Switched quotes in code.
* A staging server wouldn't be the worst idea. We've probably hit that point
=> Hotfix 2.0.1

library/Fission/App/Domain/Error.hs, library/Fission/Error/AlreadyExists/Types.hs, library/Fission/Error/NotFound/Types.hs, library/Fission/Internal/UTF8.hs, library/Fission/Types.hs, library/Fission/URL/DomainName/Types.hs, library/Fission/URL/Subdomain/Types.hs, library/Fission/User/Creator/Error.hs, library/Fission/User/Password/Error.hs, library/Fission/User/Username/Error.hs, library/Fission/Web/App/Create.hs, library/Fission/Web/App/Destroy.hs, library/Fission/Web/Auth.hs, library/Fission/Web/Auth/DID.hs, library/Fission/Web/Auth/Error.hs, library/Fission/Web/Auth/Token.hs, library/Fission/Web/Auth/Token/Bearer.hs, library/Fission/Web/Auth/Token/JWT/Claims/Error.hs, library/Fission/Web/Auth/Token/UCAN.hs, library/Fission/Web/Auth/UCAN.hs, library/Fission/Web/DNS.hs, library/Fission/Web/Error.hs, library/Fission/Web/Error/Class.hs, library/Fission/Web/Log.hs, library/Fission/Web/Ping/Types.hs, library/Fission/Web/User/Create.hs, package.yaml, web/Main.hs
All auth failures were returning `500`s. Turned out to be a quick fix. Also generalized some helpers.
```hs
127.0.0.1:65098 - - HTTP/2.0 "PUT" 
[ ("Host"         , "localhost:1337"  )
, ("User-Agent"   , "curl/7.64.1"     )
, ("Accept"       , "*/*"             )
, ("Authorization", "Bearer eyJ...Otw")
, ("Content-Type" , "application/json")
] 
"/dns/QmcYMyQmp7ZpCY5mDtGP66UbW6AZzRLrFAmnFHqjgZPTuP" 
401: "Unauthorized"" - curl/7.64.1"
```
```http
~ » curl -i --http2-prior-knowledge \
-X PUT \
-H "Authorization: Bearer eyJ...FOtw" \
-H "Content-Type: application/json" \
http://localhost:1337/dns/QmcYMyQmp7ZpCY5mDtGP66UbW6AZzRLrFAmnFHqjgZPTuP
HTTP/2 401
date: Sat, 25 Apr 2020 04:36:43 GMT
server: Warp/3.3.10
Expired
```
=> Report correct auth status code

README.md
* Fixes a wrong link to releases in the README which pointed to the fission org. instead of fission-suite.
N/A
N/A
N/A
=> Fix link to releases page in README

library/Fission/Authorization.hs, library/Fission/Authorization/Types.hs, library/Fission/Internal/Mock/Config.hs, library/Fission/Internal/Mock/Types.hs, library/Fission/URL/DomainName/Types.hs, library/Fission/URL/Types.hs, library/Fission/Web/Auth/Token/Basic.hs, library/Fission/Web/Auth/Token/JWT.hs, library/Fission/Web/Auth/Token/JWT/Proof.hs, library/Fission/Web/Auth/Token/UCAN/Resource/Scope/Types.hs, library/Fission/Web/Auth/Token/UCAN/Resource/Types.hs, library/Fission/Web/Client/JWT.hs, package.yaml, stack.yaml.lock, test/Test/Fission/Web/Auth.hs, test/Test/Fission/Web/Auth/Token.hs, test/Test/Fission/Web/Auth/Token/Bearer.hs, test/Test/Fission/Web/Auth/Token/JWT/Validation.hs, test/Test/Fission/Web/Auth/Token/UCAN/Resource.hs, test/Test/Fission/Web/Auth/Token/UCAN/Resource/Scope.hs
`rsc` ("resource") is a generalization of the UCAN v0.1.0 `scp` ("scope") parameter. The TL;DR is it no longer only refers to the filesystem, but also apps and domains. It could be used for more in the future, as well.
We're dropping support for 0.1.0, since it was effectively unreleased and this covers more use cases that we're using imminently.
=> UCAN 0.2.0 — now with `rsc` (resource)

env.yaml.example, library/Fission/Authorization.hs, library/Fission/Config/Types.hs, library/Fission/SemVer.hs, library/Fission/Types.hs, library/Fission/Web/Auth/Token/JWT/Validation.hs, package.yaml, server/Fission/Internal/Development.hs, server/Main.hs
AWS doesn't support either multi-domain TLS or TLS with nested wildcards. As a consequence, we need the following changes:
* `files.${username}.fission.name -> ${username}.files.fission.name`
* All CNAMEs now consistently at `gateway.fission.${tld}`
* Drop `ipfsGateway` from the config
And while the hood was up, bumped the supported UCAN epoch to `~1.x`, since that's the correct way to use semver 😅
=> Flip files DNS

library/Fission/AWS/Route53/Class.hs, library/Fission/Internal/Mock/Config.hs, library/Fission/Internal/Mock/Config/Types.hs, library/Fission/Internal/Mock/Types.hs, library/Fission/Types.hs, package.yaml
Currently, `foo.fission.app` and friends are only cached for 10s. This makes sense for TXT records, but CNAMEs can be cached for much longer.
Increase DNS cache length to 24 hours
Closes https://github.com/fission-suite/fission/issues/336
=> Increase TTL for CNAME records

package.yaml, test/Test/Fission/DNS.hs
The test for splitting arbitrary large DNS records was hanging
Change the arbitrary instance so it doesn't hang (using `Text.replicate`)
=> Fix DNS.splitRecord tests

library/Fission/Models.hs
We have to manually add the `verified` column to the DB since the fields can't be null
Add a default value of `false` to the schema so that the DB update can be done automatically
=> Default User.verified to false

library/Fission/DNS.hs, package.yaml, test/Test/Fission/DNS.hs
TXT records are currently sized to 256 chars, but the max record size in DNS is 255 chars
Adjust the size of TXT records to 255 chars
=> Adjust DNS TXT record size

library/Fission/CLI/Command/App/Init.hs, library/Fission/CLI/Command/Setup.hs, library/Fission/CLI/Command/Whoami.hs, library/Fission/CLI/Display/Success.hs, package.yaml
If setup fails, the key sticks around (even tho it hasn't been linked to an account) and confuses the CLI
On setup, check if the local key is associated with an account (`whoami`) instead of just if it exists. Also revamp the message to show the username that you're currently logged in with
=> Fix setup bug

library/Fission/App.hs, library/Fission/App/Creator.hs, library/Fission/App/Creator/Class.hs, library/Fission/App/Modifier.hs, library/Fission/App/Modifier/Class.hs, library/Fission/Internal/Fixture/User.hs, library/Fission/Internal/Orphanage/Bytes.hs, library/Fission/Models.hs, library/Fission/Types.hs, library/Fission/User/Creator.hs, library/Fission/User/Creator/Class.hs, library/Fission/User/Modifier.hs, library/Fission/User/Modifier/Class.hs, library/Fission/Web.hs, library/Fission/Web/App.hs, library/Fission/Web/App/Update.hs, library/Fission/Web/DNS.hs, library/Fission/Web/User/UpdateData.hs, package.yaml, server/Main.hs, stack.yaml, stack.yaml.lock
We don't currently have stats on the size of a user's storage
Track size of user's data root & size of each app in DB
IPLD keeps track of the cumulative size of a node (including the entire subtree), so we can easily query that value each time the user updates their data root or the dnslink for an app
=> File stats

library/Fission/Internal/Fixture/User.hs, library/Fission/Internal/Mock/Types.hs, library/Fission/Internal/Orphanage/RSA2048/Public.hs, library/Fission/Internal/RSA2048/Pair/Types.hs, library/Fission/Models.hs, library/Fission/Types.hs, library/Fission/User/Creator.hs, library/Fission/User/DID.hs, library/Fission/User/DID/Types.hs, library/Fission/User/Modifier.hs, library/Fission/User/Modifier/Class.hs, library/Fission/Web/Auth/Token/JWT.hs, library/Fission/Web/User.hs, library/Fission/Web/User/UpdateExchangeKeys.hs, server/Main.hs, test/Test/Fission/User/DID.hs, test/Test/Fission/Web/Auth.hs
User's need to be able to share their public exchange keys over DNS
Add a PATCH /user/exchange root
This will function similarly to PATCH /user/did
It should take an array of did:keys as a parameter, and update the TXT record at `_exchange.${username}.fission.name` to include those keys
Closes https://github.com/fission-suite/fission/issues/341
=> Exchange keys route

library/Fission/CLI/Config/Base/Types.hs, package.yaml
Remove unused line from debugging why IPFS is broken in the CLI on my NixOS system. Thanks to @brainrape for pointing it out!
=> Remove debugging printline

library/Fission/CLI/Config/Connected.hs, library/Fission/CLI/Config/Connected/Types.hs, library/Fission/CLI/Environment.hs, library/Fission/CLI/Environment/Override.hs, library/Fission/CLI/Environment/Override/Types.hs, library/Fission/CLI/IPFS/Connect.hs, package.yaml
The CLI is not connecting to our remote node
There are two fixes here:
- make sure that we're writing the entire peerlist from the server to `~/.fission.yaml` (we were just writing the tail for some reason)
- attempt connection to the entire peerlist (we were just attempting to connect to the head of the list)
=> Connect to multiple peers

library/Fission/CLI.hs, package.yaml
When a user runs a command and is not logged in we print the error twice:
```
🚫 Not logged in yet! Try running `fission setup`
🚫 Not logged in yet! Try running `fission setup`
```
This is base the error message is printed in `runConnected` & we attempt to print the error message again in another `runConnected`
Remove the extra `put'`
=> Only print connected error once

library/Fission/CLI/Command/Setup.hs, library/Fission/CLI/Command/Whoami.hs, library/Fission/CLI/Config/Connected.hs
Made a link to https://fission.codes/support consistent in most error messages, and fixed spelling
=> Error message and spelling updates

README.md
While we’re using @bmann’s machine as a build server ahead of having Nix-based cross compile, we should probably have instructions on how to do that.
=> Notes on building w/o Nix

fission-core/library/Fission/Types.hs, fission-core/package.yaml
1. Update database record
2. Set DNSLink
3. Pin
Well, in practice this is completely backwards! We have situations where the files aren’t synced, the user closes their window / stops transfer. Since the DNSLink is already set, there’s no way to get the new data.
1. Pin
2. Set DNSLink
3. Update database record
=> Set DNSLink *after* pinning

fission-cli/README.md
The stack command was reversed, also documented copying keys to new config path.
=> Stack command and CLI install instructions

.github/workflows/ci.yaml, fission-cli/library/Fission/CLI/Handler/App/Publish.hs, fission-cli/package.yaml
We updates the IPFS dir add function for publish, but not on the inner watcher loop. In retrospect, capturing this in a closure probably would make sense (but probably needs a `MonadBaseControl` instance, which is coming in the websocket linking PR).
Closes #418
=> Update publish watcher for IPFS 0.7

fission-cli/README.md
Removing the install / start `ipfs` instructions from the CLI README (now that 2.9.0 has been released)
=> Remove IPFS install instructions

shell.nix
It looks like the `hinotify` package is now part of `haskellPackages` on nixOS - small update for `shell.nix`.
=> small fix for hinotify

fission-cli/library/Fission/CLI/Prompt/BuildDir.hs, fission-cli/package.yaml
Small change to the build dir prompt to clarify (with a verb) as suggested in #420
=> clarify buildDir prompt message (#420)

fission-cli/library/Fission/CLI.hs, fission-cli/library/Fission/CLI/Handler/Setup.hs, fission-cli/library/Fission/CLI/Handler/User/Register.hs, fission-cli/library/Fission/CLI/Parser/Command/Setup.hs, fission-cli/library/Fission/CLI/Parser/Command/Setup/Types.hs, fission-cli/library/Fission/CLI/Parser/Command/User/Register.hs, fission-cli/library/Fission/CLI/Parser/Command/User/Register/Types.hs
Adds `--username` and `--email` flags to `fission user register` and `fission setup` so that user registration can be run non-interactively.
Fixes #416
=> User register non-interactive

fission-cli/library/Fission/CLI.hs, fission-cli/library/Fission/CLI/App.hs, fission-cli/library/Fission/CLI/Handler/App/Init.hs, fission-cli/library/Fission/CLI/Handler/App/Publish.hs, fission-cli/library/Fission/CLI/Handler/Setup.hs, fission-cli/library/Fission/CLI/Handler/User/Register.hs, fission-cli/library/Fission/CLI/Handler/User/Whoami.hs, fission-cli/package.yaml
When a handler errors, make sure the CLI exits with a non-zero exit code. This will help the github action report errors more accurately.
Closes #381
=> Return non-zero exit codes on failure 

fission-web-api/library/Fission/Web/API/User/Email/Resend/Types.hs, fission-web-api/library/Fission/Web/API/User/Email/Types.hs, fission-web-server/library/Fission/Web/Server.hs, fission-web-server/library/Fission/Web/Server/Challenge.hs, fission-web-server/library/Fission/Web/Server/Challenge/Retriever/Class.hs, fission-web-server/library/Fission/Web/Server/Email.hs, fission-web-server/library/Fission/Web/Server/Email/Class.hs, fission-web-server/library/Fission/Web/Server/Email/Error.hs, fission-web-server/library/Fission/Web/Server/Handler/User.hs, fission-web-server/library/Fission/Web/Server/Handler/User/Create.hs, fission-web-server/library/Fission/Web/Server/Handler/User/Email.hs, fission-web-server/library/Fission/Web/Server/Handler/User/Email/Resend.hs, fission-web-server/library/Fission/Web/Server/Handler/User/Email/Verify.hs, fission-web-server/library/Fission/Web/Server/Handler/User/ResendEmail.hs, fission-web-server/library/Fission/Web/Server/Types.hs
This is just so that it's up here.
At the moment there's still a bug in here.
When resending a verification email, I create a new challenge. So then there are multiple challenges associated with a user. But verification only `selectFirst`s the challenges.
So two solutions:
* Fetch all challenges when verifying, so `selectAll` or sth like that (possibly less secure)
* Send the same challenge when resending email verification as the one associated.
By the way - is having multiple challenges associated with a user intended? If not, couldn't it become a field of User?
---
First dip into server code yay :tada:
=> New route for resending email verification

fission-cli/library/Fission/CLI.hs, fission-cli/library/Fission/CLI/Parser/Command.hs
(Result of a pairing session with @expede )
* This adds a new shortcut for `fission whoami` (to `fission user whoami`)
* Also, will show the full `--help` text anytime the parsing fails, including just running `fission` (or `fission not-a-command`, etc)
Re: #386
=> Shortcuts and defaults ("magic" commands)

fission-web-server/env.yaml.example, fission-web-server/library/Fission/Web/Server/Config/Types.hs, fission-web-server/library/Fission/Web/Server/Environment/IPFS/Types.hs, fission-web-server/library/Fission/Web/Server/Internal/Development.hs, fission-web-server/library/Fission/Web/Server/Internal/Production.hs, fission-web-server/library/Fission/Web/Server/Types.hs
After upgrading to IPFS Cluster, we now want to return multiple peer IDs, for all the nodes in the cluster.
Change `env.yaml` so that it takes a `NonEmpty` list of remote peers. Update `/ipfs/peers` to return this list
=> Allow multiple remote peers

fission-core/library/Fission/Web/Auth/Token/UCAN/Resource/Types.hs
We parse UCANs expecting a `wnfs` path, but old versions of the CLI send it as `floofs`
Change server parser to accept both
=> Make UCANs backward compatible with FLOOFS

fission-core/library/Fission/User/Username/Types.hs, fission-core/library/Fission/User/Username/Validation.hs, fission-web-server/package.yaml
This one is fully on me
We're using the "smart constructor" technique where you don't export the base constructor, and instead use a custom function that does checks. It's a really convenient way of enforcing checks at runtime without having to like... write a constructive proof on the incoming data. The checks happen at runtime, and this are wrapped in an `Either`.
The problem here is that inside the module that declares a the data type, you have compete access to the internal field. This is also the module where (most) of your type classes live (needs to be here, or where the class itself if defined).
I created a smart constructor, but failed to update the type classes. So, `FromJSON` was able to bypass the checks and create invalid `Username`s 🤦‍♀️ That's what I get for not enforcing …
=> Enforce username checks in all tyep classes

nix/sources.json
On nixOS / nix-shell - stack was giving an error:
```
I don't know how to install GHC on your system configuration, please install manually
```
bumping our niv sources gives us the latest stack version which enables stack build/install again.
=> bump our nix sources

fission-cli/library/Fission/CLI/Release.hs
The CLI used to print an error when fission wasn't set up on the machine yet.
Now the error is converted into a `logDebug`.
=> Don't print an "Unable to parse config" warning

fission-core/library/Fission/URL/Validation.hs
Today, users are restricted to non-underscored usernames and app names (subdomains).
- Allow underscores in the validator
- disallow usernames that _start_ with underscores so that we don't have conflicts with `_did`, `_dataroot`, `_dnslink`, etc
=> Allow underscores

shell.nix
This PR fixes a small typo that was bothering me when in a nix-shell
=> Fix typo "Fisson" in shell.nix

fission-cli/package.yaml, fission-core/library/Fission/Key/Asymmetric/Algorithm/Types.hs, fission-core/package.yaml, fission-web-server/package.yaml
Use the `alg: EdDSA` in Ed25519 UCANs (per JWT spec). Still accept Ed25519 for historical UCANs.
=> UCAN: alg: "Ed25519" -> alg: "EdDSA"

nix/commands.nix
We updated the prod server, which includes a different username (`ubuntu` -> `fission`). This PR fixes the command to dial into that instance.
You will need to remove `instance.runfission.com` from `~/.ssh/know_hosts` and re-auth it before this change will work
=> Update ssh-prod command

fission-web-server/library/Fission/Web/Server/Types.hs, fission-web-server/package.yaml, nix/fission-web-server.nix
Don't create a "sample" app on account creation.
At the moment this feature is not really that useful and mostly confusing to the users. "I never created an app, why is there one?"
I set up the auth lobby on my pizza instance with this branch's code, created a new account in the lobby and ran this in the console:
=> Don't create an app on user creation

nix/commands.nix, nix/sources.json, stack.yaml, stack.yaml.lock
@walkah rejoice for `In Nix shell but reExecL is False` is no more!
In other words, we don't _need_ to use all of the custom commands from inside Nix now. You can just `stack build`.
* Bump Stack to 2.7.1 (updated Nix packages in general)
* Enable Nix integration by default
---
NOTE: remember that you'll need to `lorri shell` to get the updated Stack
=> Bump Stack to 2.7.1

fission-cli/library/Fission/CLI.hs, fission-cli/library/Fission/CLI/Handler/Setup.hs, fission-cli/library/Fission/CLI/Key/Store.hs, fission-cli/library/Fission/CLI/Parser/Command/Setup.hs, fission-cli/library/Fission/CLI/Parser/Command/Setup/Types.hs, fission-cli/package.yaml
This PR adds a `--with-key` option to `fission setup` that allows the CLI to bootstrap with a given key file (i.e. `machine_id.ed25519`). This is useful if you just back up your key file to move to a new machine or restore. It is also required to upgrade the https://github.com/fission-suite/publish-action to the latest CLI version.
This is related to #496 but an interim step, mostly to clean up the publish action in a backwards compatible way (right now the publish action takes advantage of old CLI versions that would check if there was a machine key in place already). 
Example: 
And if the key file is bad or wrong (e.g. my key from staging used against production):
=> CLI: add --with-key option to setup

fission-cli/library/Fission/CLI/IPFS/Configure.hs, fission-cli/library/Fission/CLI/IPFS/Executable.hs, fission-cli/package.yaml
This PR changes how we run `ipfs init` during setup. We already have a nice `IPFS.runLocal` wrapper that cleanly handles stdout / stderr and checks exit codes for the IPFS process. We use it everywhere *except* when calling `ipfs init`. On some platforms (sometimes?) ipfs init would not complete before the subsequent commands tried to run - resulting in error messages (ipfs repo locked). 
Fixes #499
=> Fix how setup runs ipfs init

README.md
This was fixed in Stack 2.7. You can just `stack build` now, and it defaults to building in a pure Nix environment. You can still pass it `--no-nix` for non-Nix builds.
=> Remove STACK_IN_NIX_SHELL from README

fission-cli/library/Fission/CLI/Handler/App/Publish.hs, fission-cli/package.yaml
Turns out that `forever . lifIO` is not the same as `liftIO . forever` 😅  Which makes sense. _Which thing_ are you running forever? `liftIO :: IO a -> FissionCLI a` (i.e. embed IO action in a pure data structure), so we want the conversion on the _outside_.
=> Hotfix: CLI watch flag causes hang

fission-cli/library/Fission/CLI/Handler/App/Publish.hs, fission-cli/package.yaml, fission-core/library/Fission/Internal/UTF8.hs
There's currently an issue where paths containing spaces get treated as multiple commands on `stdin`. Wrapping the path in quotes resolves this issue (confirmed on macOS and Linux). Ideally we would handle this in `ipfs-haskell`, but there's a bunch of edge cases, and honestly that library needs a larger facelift. This one-liner resolves the issue for us.
=> Fix CLI publish directory with spaces

fission-cli/library/Fission/CLI/Types.hs, fission-cli/package.yaml
IPFS 0.9 has a new `--migrate` flag on the daemon, which automigrates the repo on startup. This PR enables that flag.
I tested this manually by removing my existing repo, and setting up a new repo via my global IPFS 0.7 at the correct location (via `IPFS_PATH`), and then running `fission up`, which worked
=> Automigrate IPFS repo

fission-web-api/library/Fission/Web/API/Auth/Types.hs, fission-web-server/library/Fission/Web/Server/Environment/Server/Types.hs, fission-web-server/library/Fission/Web/Server/Internal/Orphanage/HigherOrder.hs, fission-web-server/library/Fission/Web/Server/Internal/Orphanage/RegisterDid.hs, fission-web-server/library/Fission/Web/Server/Internal/Orphanage/WebSocket.hs, fission-web-server/library/Fission/Web/Server/Internal/Production.hs, fission-web-server/package.yaml, shell.nix, stack.yaml, stack.yaml.lock
[EKG is a tool for metrics](http://maxgabriel.github.io/ekg-yesod/). There's a bunch of packages for integrating with ElasticSearch and whatnot. I figured that it may be good for us to have some of these stats even crudely in panels for checking the production environment to find bottlenecks.
Use case: as we're bumping up the number of IPFS client HTTP connections originating from the server, I'd like to see if it's actually unblocking that previous bottleneck that Philipp seemed to run into with a large number of concurrent IPFS-related requests.
As with any instrumentation, this adds some overhead to our server. According to the docs, it's generally in the range of 200-600µs.
=> Add EKG to server

fission-cli/library/Fission/CLI/Handler/App/Publish.hs, fission-cli/package.yaml, fission-cli/test/Fission/Test/CLI.hs, fission-cli/test/Fission/Test/CLI/Prelude.hs, fission-cli/test/Main.hs, fission-web-client/library/Fission/Web/Client/Error.hs
Interesting that we hadn't bumped into this previously, but yeah, we were resubmitting the exact same request every time. This PR changes the `retryOnStatus` function to re-run the request builder on retry.
Closes #549
Still writing tests, but it would be good to have this working in the meantime. The CLI changes are extremely straightforward, and continue to work in the non-timeout scenario that I can test locally. Writing tests for the 502 case, which I'll put in a separate PR
=> Generate new UCAN on CLI retry

fission-cli/library/Fission/CLI/App.hs, fission-cli/library/Fission/CLI/Connected.hs, fission-cli/library/Fission/CLI/Environment.hs, fission-cli/library/Fission/CLI/Error/Types.hs, fission-cli/library/Fission/CLI/Handler/App/Publish.hs, fission-cli/library/Fission/CLI/Handler/Error/Types.hs, fission-cli/library/Fission/CLI/Handler/User.hs
This PR resolves a few minor UX issues I ran into while using the tool today. In particular, it:
- Improves the error when running `app publish` with an unregistered app (closes #569)
- Adds a new error when running `app register` without a `config.yaml` (closes #538)
- Adds a new error when running `whoami` without a `config.yaml`
- Changes one pre-existing error message to have a consistent style with other similar error messages
Feel free to nitpick this as much as you'd like; I haven't worked with the repo before, and I'm out of practice with Haskell, so it's likely I'm missing some idioms!
In particular, I suspect some of these error strings should be pulled into `Fission.CLI.Error.Types`. Then I could probably define a helper somewhere that translates the `NotFound FilePath` into a …
=> Add new errors for a few failure cases

fission-cli/library/Fission/CLI/IPFS/Configure.hs, fission-cli/library/Fission/CLI/IPFS/Executable.hs, fission-cli/package.yaml
https://github.com/fission-suite/fission/issues/590
On conference WiFi, even 😆 Stuff appears to continue to work (and was actually extremely fast this time)
```
[nix-shell:~/Documents/Work/Fission/fission]$ fission setup
🌱 Setting up environment
🪐 Downloading managed IPFS for macOS
🕕🎛️  Configuring managed IPFS
🔑 Setting up keys
🏠 Do you have an existing account? [Y/n] n
Username: expede-devconnect-21-04-22
Email: be.zelenka@gmail.com
✅ Registration successful! Head over to your email to confirm your account.
🎛️  Initializing user config file
✅ Done! Welcome to Fission, expede-devconnect-21-04-22 ✨
[nix-shell:~/Documents/Work/Fission/fission]$ mkdir ~/Desktop/foobar
[nix-shell:~/Documents/Work/Fission/fission]$ cd ~/Desktop/foobar
[nix-shell:~/Desktop/foobar]$ echo "hello world, this is a …
```
=> go-ipfs 0.12.2 & enable hole punching

hs-ucan/library/Web/UCAN/DelegationChain.hs, hs-ucan/library/Web/UCAN/DelegationChain/StreamWithErrors.hs, hs-ucan/package.yaml, hs-ucan/test/Test/Web/UCAN/Attenuation.hs, hs-ucan/test/Test/Web/UCAN/Orphanage/DummyResolver.hs
`MonadWalk` is superseded by `Alternative`.
The `list-t` library doesn't have the `select` function that `list-transformer` has and both libraries export exactly isomorphic `ListT` types.
=> Switch to list-transformer library & remove MonadWalk

fission-cli/library/Fission/CLI.hs, fission-cli/library/Fission/CLI/Handler.hs, fission-cli/library/Fission/CLI/Handler/Generate.hs, fission-cli/library/Fission/CLI/Handler/Generate/Credentials.hs, fission-cli/library/Fission/CLI/Parser/Command.hs, fission-cli/library/Fission/CLI/Parser/Command/Generate.hs, fission-cli/library/Fission/CLI/Parser/Command/Generate/Credentials.hs, fission-cli/library/Fission/CLI/Parser/Command/Generate/Credentials/Types.hs, fission-cli/library/Fission/CLI/Parser/Command/Generate/Types.hs, fission-cli/library/Fission/CLI/Parser/Command/Types.hs, fission-cli/package.yaml
This PR adds a `fission generate credentials` command to create Ed25519 key pairs and their associated DIDs.
The credentials subcommand has no options and only generates Ed25519 key pairs
```
»  ~/.local/bin/fission generate credentials --help
Usage: fission generate credentials 
Generate an Ed25519 key pair and an associated DID
Available options:
-h,--help                Show this help text
```
The output prints a private key, public key, and DID
```
»  ~/.local/bin/fission generate credentials
✅ Generated an Ed25519 key pair and associated DID
🗝️  Private key: <private-key>
🔑 Public key: <public-key>
🆔 DID: <DID>
```
This PR also adds a top-level `generate` command with no fallbacks. It must be used with the `credentials` …
=> Add generate credentials command

fission-web-server/README.md, fission-web-server/docker-compose.yml
Better instructions for running fission server (and tools) for local development
Closes #609
=> Server readme updates

fission-cli/library/Fission/CLI/Types.hs, fission-core/library/Fission/Web/Auth/Token/UCAN.hs, fission-web-server/library/Fission/Web/Server/Error/Class.hs, fission-web-server/library/Fission/Web/Server/Types.hs, fission-web-server/package.yaml, hs-ucan/library/Web/UCAN.hs, hs-ucan/library/Web/UCAN/Error.hs, hs-ucan/library/Web/UCAN/Resolver/Class.hs, hs-ucan/library/Web/UCAN/Resolver/Error.hs, hs-ucan/library/Web/UCAN/Validation.hs, hs-ucan/package.yaml
@bgins and I ran into this problem while working on #606. The core thing is that it's impossible to actually construct a UCAN from a `RawContent` without also having a `Signature`, so `fromRawContent` could never succeed.
```haskell
UCAN.RawContent -> Either Resolver.Error (UCAN fct rsc ptc) -- 😾 How get signature?
```
I also bubbled some error content through while I had the hood up.
The one thing that isn't covered here is if `UCAN.parse` should automatically add quotes to make the JSON parsing work internally. I think not, but perhaps it would be less surprising with them?
=> Bugfix: `fromRawContent` can never succeed

fission-cli/library/Fission/CLI/Handler/Error/Types.hs, fission-web-api/library/Fission/Web/API/Append/Types.hs, fission-web-server/README.md, fission-web-server/library/Fission/Web/Server.hs, fission-web-server/library/Fission/Web/Server/App/Modifier.hs, fission-web-server/library/Fission/Web/Server/App/Modifier/Class.hs, fission-web-server/library/Fission/Web/Server/Error/Class.hs, fission-web-server/library/Fission/Web/Server/Handler/Append.hs, fission-web-server/library/Fission/Web/Server/Types.hs, ipfs/library/Network/IPFS/Client.hs, ipfs/library/Network/IPFS/Client/Files.hs, ipfs/library/Network/IPFS/Client/Files/Copy/Types.hs, ipfs/library/Network/IPFS/Client/Files/Remove/Types.hs, ipfs/library/Network/IPFS/Client/Files/Statistics/Types.hs, ipfs/library/Network/IPFS/Client/Files/Write/Form/Types.hs, ipfs/library/Network/IPFS/Client/Files/Write/Types.hs, ipfs/library/Network/IPFS/Error.hs, ipfs/library/Network/IPFS/Files.hs, ipfs/library/Network/IPFS/Files/Error.hs, ipfs/library/Network/IPFS/Remote/Class.hs, ipfs/package.yaml
This PR implements most of the functionality needed for the HTTP endpoint that appends a file to the DAG of an app.
**Based on the `append-endpoint` branch.**
- Adds various remote IPFS functions for working with the MFS
- Adds a function to add data to the DAG of an app, and another that calls it, and sets the new CID in the database + DNSLink
- Adds some additional info the server readme
This doesn't check for the correct resources in the provided UCAN, that'll be a separate PR.
```http
PUT "http://runfission.test:1337/v2/api/append/app-name/file.name"
Content-Type: application/octet-stream
Authorization: Bearer UCAN
204 No Content
```
=> Append endpoint DAG surgery

fission-cli/library/Fission/CLI/Handler/App/Init.hs
I was a bit confused and read: "on the next run, use this command instead"
Only to realize I have to do it next to have my app published 😅
=> cli: add comma to clarify instructions after app registration

fission-web-server/sql/README.md
This PR adds some more details on migrating postgres when it's running in a docker container.
Closes #627.
=> Add migration in docker container instructions

fission-web-server/package.yaml
The most recent server changes (From #625 ) didn't bump the server version making it more difficult to determine deployed versions. This PR just bumps the version in fission-web-server/package.yaml.
=> Bump server version

fission-cli/library/Fission/CLI/IPFS/Download/GitHub/Types.hs, fission-cli/library/Fission/CLI/IPFS/Executable.hs, fission-cli/library/Fission/CLI/IPFS/Release/Types.hs, fission-cli/package.yaml
Title says it all, bumping the bundled kubo version from 0.12 to 0.17 (which includes the s/go-ipfs/kubo/ rename)
=> kubo rename and bump cli to 0.17
